name: Github Actions CI
on: [push]

jobs:

    check-frontend:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./frontend

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Node JS
          uses: actions/setup-node@v3

        - name: Intall dependencies
          run: npm ci --prefer-offline

        - name: Check lint
          run: npm run lint
    
    check-node-api:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./node-api

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install Node JS
          uses: actions@setup-node@v3

        - name: Install dependencies
          run: npm ci --prefer-offline

        - name: Run lint
          run: npm run lint

        - name: Run unit tests
          run: npm run test:ci

        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v5
          with:
            token: ${{ secrets.CODECOV_TOKEN }}


    build-images:
        runs-on: ubuntu-latest
        permissions:
            packages: write
        strategy:
          matrix:
            include:
                - context_name: ./frontend
                  tag_name: ghcr.io/mrviche/cicd-project-two/frontend:latest
                - context_name: ./node-api
                  tag_name: ghcr.io/mrviche/cicd-project-two/node-api:latest
            
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GHCR_PAT }}

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ matrix.tag_name}}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: ${{ matrix.context_name }}
                push: true
                tags: ${{ matrix.tag_name }}
                cache-from: type=gha
                cache-to: type=gha, mode=max

                

