name: Github Actions CI
on: [push]

jobs:
    build-images:
        runs-on: ubuntu-latest
        permissions:
            packages: write
        strategy:
          matrix:
            include:
                - context_name: ./frontend
                  tag_name: ghcr.io/mrviche/cicd-project-two/frontend
                - context_name: ./node-api
                  tag_name: ghcr.io/mrviche/cicd-project-two/node-api
            
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GHCR_PAT }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: ${{ matrix.context_name }}
                push: true
                tags: ${{ matrix.tag_name }}:latest
                cache-from: type=gha
                cache-to: type=gha, mode=max

